spring:
  application:
    name: multi-tenant

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://testDb/multi_tenant_master_db_final?ssl=require
    username: test
    password: !test

#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml


server:
  port: 8090


application:
  tenant:
    db:
      host: test
      port: 12345
      driver: org.postgresql.Driver


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE